version: '3.8'
services:
    redis:
        image: valkey/valkey:8.0.2
        environment:
            # ALLOW_EMPTY_PASSWORD is recommended only for development.
            - ALLOW_EMPTY_PASSWORD=yes
            - VALKEY_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        ports:
            - '6380:6379'
        volumes:
            - 'valkey_data:/valkey/valkey/data'
#  mock-oauth2-server:
#    image: ghcr.io/navikt/mock-oauth2-server:0.5.1
#    ports:
#      - "8080:8080"
#    environment:
#      JSON_CONFIG: "{\"interactiveLogin\":false}"
#    hostname: host.docker.internal
#  wonderwall:
#    image: ghcr.io/nais/wonderwall:latest
#    # alternatively,
#    # build: .
#    ports:
#      - "3000:3000"
#    command: >
#      --openid.client-id=bogus
#      --openid.well-known-url=http://host.docker.internal:8080/default/.well-known/openid-configuration
#      --ingress=http://localhost:3000
#      --bind-address=0.0.0.0:3000
#      --upstream-host=upstream:4000
#      --redis.address=redis:6379
#      --redis.tls=false
#      --log-level=debug
#      --log-format=text
#    restart: on-failure
#    environment:
#      WONDERWALL_OPENID_CLIENT_JWK: ${WONDERWALL_OPENID_CLIENT_JWK} # generated from mkjwk.org and set in .env file
#  upstream:
#    image: mendhak/http-https-echo:24
#    ports:
#      - "4000:4000"
#    logging:
#      driver: none
#    environment:
#      HTTP_PORT: 4000
#      JWT_HEADER: Authorization

volumes:
    valkey_data:
        driver: local
