ingresses:
  - "https://bidrag-reisekostnad.dev.nav.no"
env:
  BIDRAG_REISEKOSTNAD_API_URL: "https://bidrag-reisekostnad-api.dev.intern.nav.no"
  BIDRAG_PERSON_URL: "https://bidrag-person-feature.dev-fss-pub.nais.io/bidrag-person"
  DEKORATOR_ENV: dev
  BIDRAG_PERSON_SCOPE: "dev-fss:bidrag:bidrag-person-feature"
  BIDRAG_REISEKOSTNAD_API_SCOPE: "dev-gcp:bidrag:bidrag-reisekostnad-api"
  REDIS_HOST: bidrag-reisekostnad-ui-redis.bidrag.svc.cluster.local
  REDIS_PORT: 6379
replicas:
  count: 1
external:
  decorator: dev.dekoratoren.nav.no