ingresses:
  - https://bidrag-reisekostnad.ekstern.dev.nav.no
env:
  BIDRAG_REISEKOSTNAD_API_URL: http://bidrag-reisekostnad-api
  BIDRAG_REISEKOSTNAD_API_SCOPE: dev-gcp:bidrag:bidrag-reisekostnad-api
  DEKORATOR_ENV: dev
replicas:
  count: 1
external:
  decorator: dekoratoren.ekstern.dev.nav.no
