
ingresses:
  - "https://bidrag-reisekostnad.dev.nav.no"
env:
  BIDRAG_REISEKOSTNADER_API_URL: "https://bidrag-reisekostnad-api.dev.intern.nav.no"
  DEKORATOR_ENV: dev
  BIDRAG_PERSON_SCOPE: "dev-fss:bidrag:bidrag-person-feature"
  BIDRAG_REISEKOSTNAD_API_SCOPE: "dev-gcp:bidrag:bidrag-reisekostnad-api"