ingresses:
  - https://bidrag-reisekostnad.ekstern.dev.nav.no
env:
  BIDRAG_REISEKOSTNAD_API_URL: bidrag-reisekostnad-api.bidrag.svc.cluster.local
  BIDRAG_REISEKOSTNAD_API_SCOPE: dev-gcp:bidrag:bidrag-reisekostnad-api
  DEKORATOR_ENV: dev
  REDIS_HOST: bidrag-reisekostnad-ui-redis.bidrag.svc.cluster.local
  REDIS_PORT: 6379
replicas:
  count: 1
external:
  decorator: dev.dekoratoren.nav.no