apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: bidrag-reisekostnad-ui
  namespace: bidrag
  labels:
    team: bidrag
    app: bidrag-reisekostnad-ui
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: "/api/nais/isalive"
    port: 3000
    initialDelay: 5
    timeout: 60
  readiness:
    path: "/api/nais/isready"
    port: 3000
    initialDelay: 5
    timeout: 60
  replicas:
    min: {{replicas.count}}
    max: {{replicas.count}}
    cpuThresholdPercentage: 50
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - "/_next/static/*/*"
  valkey:
    - instance: reisekostnad
      access: readwrite
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: bidrag-reisekostnad-api
          namespace: bidrag
        - application: nav-dekoratoren
          namespace: personbruker
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  env:
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
    - name: NPM_CONFIG_CACHE
      value: /tmp
  secureLogs:
    enabled: true