ingresses:
  - "https://bidrag-reisekostnad.nav.no"
env:
  BIDRAG_REISEKOSTNAD_API_URL: "https://bidrag-reisekostnad-api.intern.nav.no"
  BIDRAG_REISEKOSTNAD_API_SCOPE: "prod-gcp:bidrag:bidrag-reisekostnad-api"
  DEKORATOR_ENV: prod
  REDIS_HOST: bidrag-reisekostnad-ui-redis.bidrag.svc.cluster.local
  REDIS_PORT: 6379
replicas:
  count: 2
external:
  decorator: dekoratoren.nav.no