ingresses:
  - https://bidrag-reisekostnad.nav.no
env:
  BIDRAG_REISEKOSTNAD_API_URL: http://bidrag-reisekostnad-api
  BIDRAG_REISEKOSTNAD_API_SCOPE: prod-gcp:bidrag:bidrag-reisekostnad-api
  DEKORATOR_ENV: prod
replicas:
  count: 2
external:
  decorator: dekoratoren.nav.no