apiVersion: aiven.io/v1alpha1
kind: Redis
metadata:
  name: redis-bidrag-reisekostnad
  namespace: bidrag
  labels:
    app: bidrag-reisekostnad-ui
    team: bidrag
spec:
  plan: startup-4
  project: nav-dev
