name: 'Build and deploy prod'
on:
    push:
        branches:
            - 'main'
env:
    GITHUB_USERNAME: x-access-token
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    NPM_TOKEN: ${{ secrets.READER_TOKEN }}
    DEKORATOR_ENV: prod

jobs:
    build:
        permissions:
            contents: 'read'
            id-token: 'write'
        name: Install, test and build application
        runs-on: 'ubuntu-latest'
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  registry-url: 'https://npm.pkg.github.com'
            - name: Clean install of dependencies
              run: 'npm ci'
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
            - name: Run tests
              run: npm run test
            - name: Create an optimized production build of the application
              run: npm run build
            - name: Remove dev dependencies
              run: npm prune --production
            - uses: nais/docker-build-push@v0
              id: docker-push
              with:
                  team: bidrag
                  identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
                  project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
        outputs:
            image: ${{ steps.docker-push.outputs.image }}
    deployAppToProd:
        name: Deploy application to production
        needs: build
        runs-on: 'ubuntu-latest'
        steps:
            - uses: actions/checkout@v4
            - name: Deploy to PROD
              uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: prod-gcp
                  RESOURCE: .nais/nais.yaml
                  VARS: .nais/prod.yaml
                  IMAGE: ${{ needs.build.outputs.image }}
