name: 'Build and deploy prod'
on:
    push:
        branches:
            - 'main'
env:
    GITHUB_USERNAME: x-access-token
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    NPM_TOKEN: ${{ secrets.READER_TOKEN }}
    DEKORATOR_ENV: prod

jobs:
    build-and-push:
        name: Install, test, build application and push Docker image
        runs-on: 'ubuntu-latest'
        permissions:
            contents: read # required for actions/checkout
            id-token: write # required for nais/login
            actions: none # should be read according to naisdoc
        steps:
            - name: Checkout repository # under $GITHUB_WORKSPACE
              uses: actions/checkout@v4
            - name: Setup node environment
              # The setup-node action creates an .npmrc file on the runner.
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  registry-url: 'https://npm.pkg.github.com'
            - name: Clean install of dependencies
              run: npm ci
              env:
                  # Store the secret in the NPM_TOKEN environment variable.
                  NPM_TOKEN: ${{ secrets.READER_TOKEN }}
            - name: Run tests
              run: npm run test
            - name: Create an optimized production build of the application
              run: npm run build
            - name: Remove dev dependencies
              run: npm prune --production
            - name: Push docker image to GAR and sign image
              uses: nais/docker-build-push@v0
              id: docker-push
              with:
                  team: bidrag
        outputs:
            image: ${{ steps.docker-push.outputs.image }}
    deployAppToProd:
        name: Deploy application to production
        needs: build-and-push
        runs-on: 'ubuntu-latest'
        permissions:
            contents: read
            # Requesting the JWT.
            id-token: write # required for nais/login
            actions: read
        steps:
            - name: Deploy to PROD
              uses: nais/deploy/actions/deploy@v2
              env:
                  CLUSTER: prod-gcp
                  RESOURCE: .nais/nais.yaml
                  VARS: .nais/prod.yaml
                  IMAGE: ${{ needs.build-and-push.outputs.image }}
